name: ca-certificates.crt

on:
  push:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  cmp:
    uses: ./.github/workflows/compare.yml
    with:
      pre: |
        echo 'deb [trusted=yes] http://deb.debian.org/debian/ testing main' | sudo tee /etc/apt/sources.list
        sudo apt-get update
      new: $(sudo apt-get install ca-certificates | awk '/G/ {print $7}')

  git:
    needs: cmp
    uses: WaterLemons2k/.github/.github/workflows/git.yml@main
    with:
      run: |
        echo "${{ needs.cmp.outputs.version }}"
      commit_message: ''
