name: ca-certificates.crt

on:
  push:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  cmp:
    uses: WaterLemons2k/.github/.github/workflows/compare.yml@main
    with:
      new: $(sudo apt-get install ca-certificates | grep ubuntu | awk -F '[(u]' '{print $2}')

  git:
    needs: cmp
    uses: WaterLemons2k/.github/.github/workflows/git.yml@main
    with:
      run: |
        echo "${{ needs.cmp.outputs.version }}"
      commit_message: ''
